
---
  title: "Bellabeat Case Study with R"
author: "Ece GAZİOĞLU"
date: "05-21-2024"
output:
  html_document:
  number_sections: true
toc: true
---
  
  ## ASK PHASE
  
  ### BUSINESS TASK
  
  Nowadays, smart devices can track various types of data, such as menstrual cycles, sleep, hydration, and more. The main task is to examine how people use their smart devices and identify usage trends for these features. This analysis aims to determine which features are most used and appealing to users and which features should be prioritized for improvement or development in Bellabeat products.

Since the main stakeholders, Urška Sršen and Sando Mur, who are the Chief Creative Officer and the Chief Executive Officer,and Bellabeat Marketing Analytics team, they need insights into which features require enhancement and increased investment. By analyzing smart device usage data, I can identify which features or trackers are used the most, the time periods of their usage, and their frequency of use. Additionally, these trends will aid in improving Bellabeat's marketing strategy by highlighting the least used features (possibly due to user confusion or lack of awareness). Promoting and advertising these underutilized features can help Bellabeat products gain a competitive edge.

## PREPARE PHASE 

### DATASET

  The data source used for this case study is FitBit Fitness Tracker Data. This dataset stored in Kaggle and was made available through Möbius.
  These datasets were generated by respondents to a distributed survey via Amazon Mechanical Turk between 03.12.2016-05.12.2016. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring. Variation between output represents use of different types of Fitbit trackers and individual tracking behaviors / preferences.
The data set contains 29 CSV files organized in long format. 

* Reliability: The data comes from 30 fitbit users who consented to the submission of personal tracker data.
* Original: Third party data collect using Amazon Mechanical Turk.
* Comprehensive: The dataset contains multiple fields on daily activity intensity, calories burned, steps taken, amount of sleep and weight logs.
* Current: This data is from March 2016 through May 2016. The data is not current.
* Cited: Unknown,third party data.

## PROCESS PHASE 

### INSTALLING PACKAGES
```{r,warning=F,message=F,results='hide'}
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(janitor)
library(readr)
```
### IMPORTING DATASETS
```{r,warning=F,message=F,results='hide'}
dailyActivity_merged1 <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_3.12.16-4.11.16/Fitabase Data 3.12.16-4.11.16/dailyActivity_merged.csv")
dailyActivity_merged2 <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv")
sleepDay_merged <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv")
weightLogInfo_merged1 <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_3.12.16-4.11.16/Fitabase Data 3.12.16-4.11.16/weightLogInfo_merged.csv")
weightLogInfo_merged2 <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv")
hourlyIntensities_merged1 <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_3.12.16-4.11.16/Fitabase Data 3.12.16-4.11.16/hourlyIntensities_merged.csv")
hourlyIntensities_merged2 <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/hourlyIntensities_merged.csv")
```
### PREVIEWING DATASETS
```{r,message=F,warning=F}
## there are two daily activity tables

head(dailyActivity_merged1) ## 457 rows, 15  variables
head(dailyActivity_merged2) ## 940 rows, 15 variables

## they have the same column names

rbind(dailyActivity_merged1,dailyActivity_merged2) %>%
  group_by(Id,ActivityDate,TotalSteps,TotalDistance) %>% 
  summarize(count=n()) %>% 
  filter(count>1) 

## we can combine these tables

daily_activity <- rbind(dailyActivity_merged1,dailyActivity_merged2)

## 1397 rows, 15 variables

head(sleepDay_merged) ## 413 rows, 5 variables

## there are two weight tables
head(weightLogInfo_merged1) ## 33 rows, 8  variables
head(weightLogInfo_merged2) ## 67 rows, 8 variables

## they have the same column names

rbind(weightLogInfo_merged1,weightLogInfo_merged2) %>%
  group_by(Id,Date,WeightKg,BMI) %>% 
  summarize(count=n()) %>% 
  filter(count>1) ## there will be 2 duplicate values because although weightlogınfo_merged 1 should not contain 4-12-2016 datas
## we can combine these tables

weightlog <- rbind(weightLogInfo_merged1,weightLogInfo_merged2)
head(weightlog) ## 100 rows, 8 variables

## there are two hourly intensities tables
head(hourlyIntensities_merged1) ## 24084 rows, 4 variables
head(hourlyIntensities_merged2) ## 22099 rows, 4 variables

## they have the same column names

rbind(hourlyIntensities_merged1,hourlyIntensities_merged2) %>%
  group_by(Id,ActivityHour,TotalIntensity,AverageIntensity) %>% 
  summarize(count=n()) %>% 
  filter(count>1) 
## if we combine these tables, we will have 175 duplicate values
## because hourlyIntensities should not contain 4-12-2016 observations.

hourly_intensities<- rbind(hourlyIntensities_merged1,hourlyIntensities_merged2)
head(hourly_intensities) ## 46183 rows, 4 variables
```

Now, we have 4 datasets;

+ daily_activity
+ sleepDay_merged
+ weightlog
+ hourly_intensities

### CLEANING AND FORMATING DATASETS

#### CLEANING AND RENAMING COLUMNS AND DATASETS
```{r,message=F,warning=F,results='hide'}
## first of all, i want to rename some tables because of convenience, and then, clean and rename columns

daily_activity <- daily_activity
daily_sleep <- sleepDay_merged
weight_log <- weightlog
hourly_intensities <- hourly_intensities

clean_names(daily_activity)
daily_activity<- rename_with(daily_activity, tolower)
clean_names(daily_sleep)
daily_sleep <- rename_with(daily_sleep, tolower)
clean_names(weight_log)
weight_log <- rename_with(weight_log, tolower)
clean_names(hourly_intensities)
hourly_intensities <- rename_with(hourly_intensities, tolower)

str(daily_activity)
str(daily_sleep)
str(weight_log)
str(hourly_intensities)
```
#### DETERMINING NUMBER OF USERS 
```{r}
n_distinct(daily_activity$id)
n_distinct(daily_sleep$id)
n_distinct(weight_log$id)
n_distinct(hourly_intensities$id)
```
#### DETECTING AND CONTROLLING NA'S
```{r,message=F,warning=F,results='hide'}
summary(daily_activity) ## no NA's
summary(daily_sleep) ## no NA's
summary(weight_log) ## 96 NA's in weight_log$fat, 
## since weight_log table contains 100 observation, only 4 observation of "fat" variable is not enough, 
## therefore I'm not going to use this variable in my analysis.
summary(hourly_intensities) ## no NA's
```
#### DETECTING DUPLICATES
```{r,message=F,warning=F}
daily_activity %>% 
  group_by(id,activitydate,totalsteps,totaldistance,trackerdistance) %>% 
  summarize(count=n()) %>% 
  filter(count>1) ## no duplicates 

daily_sleep %>% 
  group_by(id,sleepday,totalminutesasleep,totaltimeinbed) %>% 
  summarize(count=n()) %>% 
  filter(count>1) ## there are 3 duplicate values, let's get rid of them.

nrow(daily_sleep)
daily_sleep_unique <- unique(daily_sleep,by=c("id","SleepDay","totalminutesasleep","totaltimeinbed"))
nrow(daily_sleep_unique)

weight_log %>% 
  group_by(id,date,weightkg,weightpounds,bmi) %>% 
  summarize(count=n()) %>% 
  filter(count>1) ## there are 2 duplicate values

nrow(weight_log)
weight_log_unique <- unique(weight_log,by=c("id","date","weightkg","weightpounds","bmi"))
nrow(weight_log_unique)

hourly_intensities %>% 
  group_by(id,activityhour,totalintensity,averageintensity) %>% 
  summarize(count=n()) %>% 
  filter(count>1) ## there are 175 duplicates, 
## it's higher than other tables but this table is hourly and has 46183 observations

nrow(hourly_intensities)
hourly_intensities_unique <- unique(hourly_intensities,by=c("id","activityhour","totalintensity","averageintensity"))
nrow(hourly_intensities_unique)
```
#### MAKING COLUMNS IN A CONSISTENT FORMAT
```{r}
glimpse(daily_activity) ## activity date column, contains only date info, in character format
glimpse(daily_sleep_unique) ## sleepday column, contains date and time info, in character format
glimpse(weight_log_unique) ## date column, contains date and time info, in character format
glimpse(hourly_intensities_unique) ## activityhour column, contains date and time info, in character format

daily_activity$activitydate <- mdy(daily_activity$activitydate)
daily_sleep_unique$sleepday <- mdy_hms(daily_sleep_unique$sleepday)
weight_log_unique$date <- mdy_hms(weight_log_unique$date)
hourly_intensities_unique$activityhour <- mdy_hms(hourly_intensities_unique$activityhour)
```
#### MERGING DATASETS

In order to detect some trends and relations, 
i.e. daily activity and sleep routines relationship, 
i decided to join daily_activity and daily_sleep_unique tables
```{r,message=F,warning=F}
daily_activity_sleep <- daily_activity %>% 
  full_join(daily_sleep_unique,join_by("id"=="id","activitydate"=="sleepday"))
```

## ANALYZE & SHARE PHASE

weight_log_unique
```{r}
weight_log_unique %>% 
  group_by(id) %>% 
  summarize(min(date),
            max(date),
            duration=max(day(date))-min(day(date)),
            min(weightkg),
            max(weightkg),
            change=max(weightkg)-min(weightkg)) %>% 
  arrange(desc(duration))
```
3 people used this feature for +20 days
6 people logged and never used again
7 people out of all 13 users' weight is changed very mildly
weight tracking is the least used feature

total steps
```{r}
daily_activity %>% 
  group_by(id) %>% 
  summarize(uavgstep=mean(totalsteps)) %>% 
  summarize(sum(uavgstep<10000))

daily_activity %>% 
  group_by(activitydate) %>% 
  summarize(uavgstep=mean(totalsteps)) %>% 
  summarize(sum(uavgstep<8000))
```

According to CDC, adults should aim for 10000 steps per day. 
Average total steps per day are 6490.
According to the CDC research, taking 8,000 steps per day lower the risk by 51% for all-cause mortality (or death from all causes). 
Out of 35, 28 users (52% of users) take less than 8000 step averagely per day.
```{r}      
daily_activity%>%
  group_by(id) %>% 
  summarize(avgstep=mean(totalsteps)) %>% 
  mutate(stephealthrange=case_when(avgstep<3000 ~"highly inactive, below 3000 steps",
                                   avgstep>= 3000 & avgstep<8000 ~"needs to be more active, between 3000-8000 steps",
                                   avgstep>= 8000 & avgstep<10000 ~"active, equal or more than 8000 steps",
                                   avgstep>=10000 ~"highly active, equal or more than 10000 steps")) %>% 
  group_by(stephealthrange) %>% 
  summarize(perc=(n()/35)*100) %>% 
  ggplot(aes(x=stephealthrange,y=perc,fill=stephealthrange))+
  geom_col()+
  theme(axis.text.x = element_blank())+
  labs(title="Daily Average Step",
       x="Step per day, Average",
       y="User Percentage")
```

Out of 35 users, 14 of them (40%) are taking healthy amount of steps per day, averagely.
17.1% of users are not taking even 3000 steps per day, averagely.

Calories
```{r,message=F,warning=F}
summary(daily_activity$calories)
daily_activity %>% 
  group_by(id) %>% 
  summarize(avgcal=mean(calories),
            avgsteps=mean(totalsteps)) %>% 
  ggplot(aes(x=avgsteps,y=avgcal)) + geom_point()+geom_smooth(method="lm",se=FALSE)+
  labs(title="Average Steps Taken versus Average Calories Burned",
       x="Average Steps per User",
       y="Average Burned Calories per User")
```

Here, there is a positive correlation 
between users' average steps per day and users' average burned calories per day.

sleep
```{r}
daily_activity_sleep %>% 
       group_by(id) %>% 
       filter(!is.na(totalsleeprecords)& !is.na(totalminutesasleep)& !is.na(totaltimeinbed)) %>% 
       summarize(duration=max(day(activitydate))-min(day(activitydate))) %>% 
       arrange(desc(duration))
```

Out of 24 users, 17 users used this feature for 20+ days, 
5 users used for 10-20 days, 
2 users used for 0-5 days
```{r}
daily_activity_sleep %>% 
  group_by(id) %>% 
  filter(!is.na(totalsleeprecords)& !is.na(totalminutesasleep)& !is.na(totaltimeinbed)) %>% 
  summarize(avgsleep=mean(totalminutesasleep)/60) %>% 
  ggplot(aes(x=avgsleep))+geom_histogram(bins = 24,color="white")+
  labs(title="Sleep Amount",
       x="average sleep amount in hours of users per day",)
```

Users sleep 380 minutes per day, averagely.
according to american heart association - heart.org, 
for adults 7-9 hours of sleep per day is healthy
12 users sleep less than 7 hours per day, averagely.
12 users sleep 7 hours or more per day, averagely.
3 users sleep less than 3 hours per day, averagely.
```{r}
daily_activity_sleep %>% 
  group_by(id) %>% 
  filter(!is.na(totalsleeprecords)& !is.na(totalminutesasleep)& !is.na(totaltimeinbed)) %>% 
  summarize(avgbedws=mean(totaltimeinbed-totalminutesasleep))%>% 
  ggplot(aes(x=avgbedws))+
  geom_histogram(binwidth = 10,color="white")+
  coord_cartesian(xlim = c(0,45))+
  labs(title="Average Time in Bed without Sleeping",
       x="average minutes in bed without sleep of users")
```

Users stay in bed without sleeping averagely 42.6 minutes per day.
2 users stay in bed without sleeping averagely over than 2 hours. 
if we accept that users exceptional, average stay in bed without sleeping is approximately 25 minutes per day
```{r,message=F,warning=F}
daily_activity_sleep %>% 
  group_by(id) %>% 
  filter(!is.na(totalsleeprecords)& !is.na(totalminutesasleep)& !is.na(totaltimeinbed)) %>% 
  summarize(avgseden=mean(sedentaryminutes),
            avgsleep=mean(totalminutesasleep)) %>% 
  ggplot(aes(x=avgseden,y=avgsleep))+
  geom_point()+
  geom_smooth(method="lm",se=F)+
  labs(title="Average Sedentary Minutes versus Average Minutes Asleep per User",
       x="Average Sedentary Minutes",
       y="Average Minutes Asleep ")
```

As we can see, when a user's sedentary minutes in a day increase, asleep minutes decreases
```{r,message=F,warning=F}
daily_activity_sleep %>% 
  mutate(activeminutes=lightlyactiveminutes+fairlyactiveminutes+veryactiveminutes) %>% 
  group_by(id) %>% 
  filter(!is.na(totalsleeprecords)& !is.na(totalminutesasleep)& !is.na(totaltimeinbed)) %>% 
  summarize(avgact=mean(activeminutes),
            avgsleep=mean(totalminutesasleep)) %>% 
  ggplot(aes(x=avgact,y=avgsleep))+
  geom_point()+
  geom_smooth(method="lm",se=F)+
  labs(title="Average Active Minutes versus Average Minutes Asleep per User",
       x="Average Active Minutes",
       y="Average Minutes Asleep")
```

we can not say more activity causes better sleep since apparently better sleep has other variables, 
but according to slope, less activity can definitely cause poor sleep routine.

Activity
```{r}
daily_activity_sleep %>% 
  mutate(activeminutes=lightlyactiveminutes+fairlyactiveminutes+veryactiveminutes) %>% 
  group_by(days=wday(activitydate,label=T,locale = "ENG")) %>% 
  summarize(avgactivemin=mean(activeminutes),
            avgsedmin=mean(sedentaryminutes),
            avglightmin=mean(lightlyactiveminutes),
            avgfairmin=mean(fairlyactiveminutes),
            avghighmin=mean(veryactiveminutes)) %>% 
  arrange(desc(avgactivemin))
```
```{r}
daily_activity_sleep %>% 
  mutate(activeminutes=lightlyactiveminutes+fairlyactiveminutes+veryactiveminutes) %>% 
  group_by(days=wday(activitydate,label=T,locale = "ENG")) %>% 
  summarize(avgactivemin=mean(activeminutes),
            avgsedmin=mean(sedentaryminutes),
            avglightmin=mean(lightlyactiveminutes),
            avgfairmin=mean(fairlyactiveminutes),
            avghighmin=mean(veryactiveminutes)) %>%
  ggplot(aes(x=days,y=avgactivemin/60))+
  geom_col()+
  coord_cartesian(ylim=c(3,4))+
  labs(title = "How many hours do users active by days?",
       y="average active hours")
```

Users most active day is Saturday, its accurate because it is weekend, 
users might be choose to be more active and do some sports-like activities, but
least active day is Sunday, probably users choose resting on Sundays. for further analysis, we need to look at hourly intensities
```{r}
hourly_intensities_unique %>% 
  group_by(days=wday(activityhour,label=T,locale = "ENG")) %>% 
  summarize(avgint=mean(totalintensity)) %>% 
  arrange(desc(avgint))
```
```{r}
hourly_intensities_unique %>% 
  group_by(days=wday(activityhour,label=T,locale = "ENG")) %>% 
  summarize(avgint=mean(totalintensity)) %>% 
  ggplot(aes(x=days,y=avgint))+
  geom_col()+
  coord_cartesian(ylim=c(8,12))+
  labs(title="Average Total Intensity By Days",x="Days",y="Average Total Intensity")
```

Now, we can say that, users are more active and do sports-like activities on Saturdays
```{r}
hourly_intensities_unique %>% 
  group_by(hours=hour(activityhour)) %>% 
  summarize(avgint=mean(totalintensity)) %>% 
  arrange(desc(avgint))
```
```{r,warning=F,message=F}
hourly_intensities_unique %>% 
  group_by(hours=hour(activityhour)) %>% 
  summarize(avgint=mean(totalintensity)) %>% 
  arrange(desc(avgint)) %>% 
  ggplot(aes(x=hours,y=avgint))+
  geom_col()+
  geom_vline(xintercept =16.5,color="red",size=1.5)+
  scale_x_continuous(breaks=c(4,8,12,16,20,24))+
  labs(title="Average Total Intensity By Hours",x="Hours",y="Average Total Intensity")
```

we can say users are more active after their working hours.

## ACT PHASE

Bellabeat is a high-tech manufacturer of health-focused products for women. Collecting data on activity, sleep, stress, and reproductive health has allowed Bellabeat to empower women with knowledge about their own health and habits. Since it was founded in 2013, Bellabeat has grown rapidly and quickly positioned itself as a tech-driven wellness company for women.

After analyzing the data, I came up with some recommendations for Bellabeat marketing strategy based on trends in smart device usage.

* Weight tracking is the least used feature, 3 people used this feature for +20 days, 6 people logged and never used again. Maybe Bellabeat can consider to make some encouraging advertising for weight tracker and change user interface of weight tracking more simple, more joyful and encouraging with some tips for users who want to control/lose/gain hers/his weight.

* According to CDC, adults should aim for 10000 steps per day. 
In our analysis we saw that, average total steps per day are 6490.
According to the CDC research, taking 8,000 steps per day lower the risk by 51% for all-cause mortality (or death from all causes). 
Out of 35, 28 users (52% of users) take less than 8000 step averagely per day.
Bellabeat can suggest users to take at least 8,000 steps per day with some notifications and explain the benefits of it.

* Users sleep 380 minutes per day, averagely. According to American Heart Association - heart.org, for adults 7-9 hours of sleep per day is healthy.
our ot 24 users, 12 users sleep less than 7 hours per day, averagely.
According to our analysis, when a user's sedentary minutes in a day increase, asleep minutes decreases.We can not say more activity causes better sleep since apparently better sleep has other variables,but,less activity can definitely cause poor sleep routine. If users want to improve the quality of their sleep, Bellabeat should consider using app notifications reminding users to get enough rest, as well as recommending reducing sedentary time.

* According to intensities, we can say that, users are more active and do sports-like activities on Saturdays.Also, users are more active after their working hours. Bellabeat can use this knowledge to remind users to go for a walk or a jog on that day and after work hours. Participants seem to be the least active on Sundays. Bellabeat can use this to motivate users to go out and exercising on Sundays.

